server:
  port: 8080
  tomcat:
    max-connections: 20000
    max-threads: 400
    min-spare-threads: 20
spring:
  jackson:
    time-zone: GMT+8
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
  datasource:
    initialization-mode: ALWAYS
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://localhost:3306/boot-quick?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      initial-size: 3
      max-active: 15
      min-idle: 3
      max-wait: 5000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      poolPreparedStatements: true
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
      max-open-prepared-statements: 20
      async-init: true

  messages:
    basename: exception/exception
    use-code-as-default-message: true

#  redis:
#    cluster:
#      max-redirects: 3
#      nodes: localhost:6601,localhost:6602,localhost:6603
#    database: 0
#    jedis:
#      pool:
#        max-active: 100
#        max-idle: 10
#        min-idle: 0
#        max-wait: 800ms
#    timeout: 1000ms


  mail:
    username: 1041765757@qq.com                # 用来验证授权的邮件用户名
    password: gotartrfwuytbcji                # 根据QQ邮箱设置-账户里生成的第三方登陆授权码，可用来代替密码登陆
    host: smtp.qq.com                         # 邮件服务器类型
    properties.mail.smtp.ssl.enable: true # 用以支持授权码登陆

  rabbitmq:
    addresses: localhost:5672
    username: admin
    password: 123456
    virtualHost: /
    cache:
      channel:
        size: 100
        checkoutTimeout: 3000
      connection:
        mode: connection
        size:
    template:
      retry:
        enabled: true
        maxAttempts: 5
        initialInterval: 2000  # 第一次和第二次尝试传递消息之间的持续时间

#  rabbitmq:
#    addresses: localhost:5672
#    username: root
#    password: password
#    virtual-host: / # 创建的虚拟主机，可以简单理解为一个实例，所有队列交换器路由等都是在它的基础上，默认为/，最好自己新建一个
#    publisher-confirms: true # 消息被投递之后如何确保一定被正确投递或消费，开启conform模式
#    listener:
#      direct:
#        acknowledge-mode: manual  # 开启手动ack
#      simple:
#        acknowledge-mode: manual # 开启手动ack
#        retry:
#          enabled: false
#          max-attempts: 3
#          initial-interval: 3000 # 第一次和第二次尝试传递消息之间的持续时间
#        default-requeue-rejected: false


customs:  # 自定义的属性最好都写在custom前缀下，方便辨认
  global-properties:
    snowflakeWorkerId: 1      # worker Id can't be greater than 31 or less than 0
    snowflakeDataCenterId: 1  # dataCenterId Id can't be greater than 31 or less than 0
  jwt:
    secret: WoshiyigefenshuajiangfenshuabenlingqiangwoyaobanaxinfangzishuadegengpiaoliangshualefangziyoushuangqiangaiyawodexiaobizibianyabianleYang
    expiredMinute: 1080
    refreshTokenMinute: 10
    ignores:
      - path: /v2/*
      - path: /swagger-ui.html
      - path: /swagger-ui.html/*
      - path: /swagger-resources/**
      - path: /swagger/**
      - path: /webjars/**
      - path: /druid/**
      - path: /csrf
      - path: /app.js
      - path: /index.html
      - path: /websocket.html
      - path: /js/*
      - path: /ws/*
      - path: /pay-ws/*
      - path: /merchantBaseDevice/bindingDevice
      - path: /heartCheck.txt
  rsa:
    primaryKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIPT0VbUrdYMIX//tgHgaMh9PUtqG6R/lNOvIl9LR6Mbc5J03qjvLlu2IifHFbFonm6XguZG4LZ4H3hRkX9fC4qSaQR1vZBOvS1aNLRyvMZudISJygiag1qJOQMEwrb8JUZkP7NMpBNjYpmF344+25Il3axRnd1oVR4Hhp4tqEe1AgMBAAECgYBYv0i3BAbjitcirKuDJ+hi0K1rD8v8OkefGtAxByT7EYgEmNktMZgr9bmYvdZE0QGXwjhFfoHZVZUaEw+4h+vkJrXxv2FQHqTSL8fDeL4jggNO3YYpLFoq9bvwWeqDJ3vvVkJEbNycfoE6iXv91mUM3hb7ie1NlvWYOJtiAxf0AQJBAOzyLcea/8Au8nVnJrVstpVaItkib7pT/9w2BDAe821JTXsmUCGw47LpYHZos6G8pR9Hz8VRaj99z8Z5xa2fe2ECQQCObaUe0n67ddr3OExVF9LyFVEdGzvuOwJjQi6/URvhrQDV31kld2z9lqV6p2l6JpDpmQIwPsJTS7qbLLhjGqDVAkEAz+Gh3I/Wdiw6OFqpkV6xydLs5AfccmMkBXW2sulUtLstKTBx+T0SaHNsWDZ/8xRo4krEtN87Ej01P3KyxiM3wQJAaJirF5ycR40AtmeY3zD00KXJAOgcNhMN6NkUvZmSMUS9BVPWAwbWetEkS5QgiP1DlNmyWr3sNgG6U/UeoGFQ1QJAZief8zE0C5jCmWf7VwfAJCSd+r+BVcSCpUxskc3gnhfG6j+ImAirhXIY+ld8rArmGl4UPkQfapBphUJslWLpLg==
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCD09FW1K3WDCF//7YB4GjIfT1Lahukf5TTryJfS0ejG3OSdN6o7y5btiInxxWxaJ5ul4LmRuC2eB94UZF/XwuKkmkEdb2QTr0tWjS0crzGbnSEicoImoNaiTkDBMK2/CVGZD+zTKQTY2KZhd+OPtuSJd2sUZ3daFUeB4aeLahHtQIDAQAB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com.ddf.boot.quick.mapper: debug

management:
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    jolokia:
      enabled: true