server:
  port: 8080
  tomcat:
    max-connections: 20000
    max-threads: 400
    min-spare-threads: 20
spring:
  jackson:
    time-zone: GMT+8
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
  datasource:
    initialization-mode: ALWAYS
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druidProperties:
      username: root
      password: 123456
      url: jdbc:p6spy:mysql://localhost:3306/boot-quick?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
      name: druid
      initialSize: 3
      minIdle: 3
      maxActive: 15
      maxWait: 5000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall,slf4j
      logSlowSql: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      asyncInit: true
      connectionProperties:
        druid.stat.slowSqlMillis: 3000

  messages:
    basename: exception/exception
    use-code-as-default-message: true

#  redis:
#    cluster:
#      max-redirects: 3
#      nodes: localhost:6601,localhost:6602,localhost:6603
#    database: 0
#    jedis:
#      pool:
#        max-active: 100
#        max-idle: 10
#        min-idle: 0
#        max-wait: 800ms
#    timeout: 1000ms


  mail:
    username: 1041765757@qq.com                # 用来验证授权的邮件用户名
    password: gotartrfwuytbcji                # 根据QQ邮箱设置-账户里生成的第三方登陆授权码，可用来代替密码登陆
    host: smtp.qq.com                         # 邮件服务器类型
    properties.mail.smtp.ssl.enable: true # 用以支持授权码登陆

#  rabbitmq:
#    addresses: localhost:5672
#    username: root
#    password: password
#    virtual-host: / # 创建的虚拟主机，可以简单理解为一个实例，所有队列交换器路由等都是在它的基础上，默认为/，最好自己新建一个
#    publisher-confirms: true # 消息被投递之后如何确保一定被正确投递或消费，开启conform模式
#    listener:
#      direct:
#        acknowledge-mode: manual  # 开启手动ack
#      simple:
#        acknowledge-mode: manual # 开启手动ack
#        retry:
#          enabled: false
#          max-attempts: 3
#          initial-interval: 3000 # 第一次和第二次尝试传递消息之间的持续时间
#        default-requeue-rejected: false


customs:  # 自定义的属性最好都写在custom前缀下，方便辨认
  global-config:
    anonymousName: SYSTEM
    initPassword: 123456
    platformCompCode: 0



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com.ddf.scaffold.logic.mapper: debug

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    jolokia:
      enabled: true