
# 在spring-boot应用中（注意不是spring-cloud），开启这个可以让spring-boot应用具备在启动前就将外部配置加载到spring环境中的能力， 即可通过外部配置各种数据源了
nacos:
  config:
    server-addr: ${nacos_server}
    username: ${nacos_username}
    password: ${nacos_password}
    bootstrap:
      enable: true

server:
  port: 8080
  tomcat:
    max-connections: 10000
    max-threads: 200
    min-spare-threads: 20
  servlet:
    context-path: /boot-quick

spring:
  profiles:
    active: dev
  application:
    name: boot-quick
logging:
  level:
    root: info
    com.ddf.boot.common.log.AccessLogAspect: debug
    #    com.ddf.boot.quick.mapper: debug   因为用了sql插件，这里可以先注释掉
    com.ddf.boot.common.mq: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug
