## nacos
nocos_server: 106.15.10.135:8848
nacos_username: nacos
nacos_password: Aa&123456

# 在spring-boot应用中（注意不是spring-cloud），开启这个可以让spring-boot应用具备在启动前就将外部配置加载到spring环境中的能力， 即可通过外部配置各种数据源了
nacos:
  config:
    bootstrap:
      enable: true

spring:
  profiles:
    active: dev

logging:
  level:
    root: info
    com.ddf.boot.common.log.AccessLogAspect: debug
    #    com.ddf.boot.quick.mapper: debug   因为用了sql插件，这里可以先注释掉
    com.ddf.boot.common.mq: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug
