
# 在spring-boot应用中（注意不是spring-cloud），开启这个可以让spring-boot应用具备在启动前就将外部配置加载到spring环境中的能力， 即可通过外部配置各种数据源了
nacos:
  config:
    # nacos的服务器信息可以放到启动脚本中，其它配置文件托管到配置中心
    server-addr: ${nacos_server}
    username: ${nacos_username}
    password: ${nacos_password}
    bootstrap:
      enable: true

server:
  port: 8080
  tomcat:
    threads:
      max: 400
      min-spare: 20
    max-connections: 10000
    processorCache: 400
    acceptCount: 200  # 最大等待队列长度
  servlet:
    context-path: /boot-quick
  shutdown: graceful # 配置web容器优雅关闭，https://docs.spring.io/spring-boot/docs/2.5.7/reference/htmlsingle/#features.graceful-shutdown
# 老版本
#    max-threads: 200
#    min-spare-threads: 20

spring:
  lifecycle:
    timeout-per-shutdown-phase: 60  # 优雅关闭等待时间，https://docs.spring.io/spring-boot/docs/2.5.7/reference/htmlsingle/#features.graceful-shutdown
  profiles:
    active: dev
  application:
    name: boot-quick
logging:
  level:
    root: info
    com.ddf.boot.common.log.AccessLogAspect: debug
    #    com.ddf.boot.quick.mapper: debug   因为用了sql插件，这里可以先注释掉
    com.ddf.boot.common.mq: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug
