server:
  port: 8080
  tomcat:
    max-connections: 20000
    max-threads: 400
    min-spare-threads: 20
  servlet:
    context-path: /boot-quick
spring:
  profiles:
    active: local
  application:
    name: boot-quick
  jackson:
    time-zone: GMT+8
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN

  # 国际化资源文件
  messages:
    basename: exception/exception
    use-code-as-default-message: false

customs: # 自定义的属性最好都写在custom前缀下，方便辨认
  global-properties:
    snowflakeWorkerId: 1      # worker Id can't be greater than 31 or less than 0
    snowflakeDataCenterId: 1  # dataCenterId Id can't be greater than 31 or less than 0
    ignoreErrorTraceProfile: # 过滤将异常堆栈信息输出打前端接口返回值的环境
      - pre
      - prod
  response:
    package: com
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: null
      logic-delete-field: isDel
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    # https://mp.baomidou.com/config/#localcachescope
    localCacheScope: STATEMENT
  ## mapper.xml文件所在路径
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com.ddf.boot.common.log.AccessLogAspect: debug
    #    com.ddf.boot.quick.mapper: debug   因为用了sql插件，这里可以先注释掉
    com.ddf.boot.common.mq: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug

management:
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    jolokia:
      enabled: true
