# redis相关
redis.host: 127.0.0.7
redis.port: 6379

# zookeeper相关配置
zk.host: 127.0.0.1
zk.port: 2181

# mysql 主数据源
mysql.master.host: localhost
mysql.master.port: 3306
mysql.master.db: boot-quick
mysql.master.username: root
mysql.master.password: 123456

# mysql 从1数据源
mysql.slave1.host: localhost
mysql.slave1.port: 3306
mysql.slave1.db: boot-quick-slave1
mysql.slave1.username: root
mysql.slave1.password: 123456



# rabbitmq相关
rabbit.address: localhost:5672
rabbit.username: guest
rabbit.password: guest

# leaf雪花算法zookeeper地址
leaf.address: localhost
leaf.port: 2181


server:
  port: 8080
  tomcat:
    max-connections: 20000
    max-threads: 400
    min-spare-threads: 20
  servlet:
    context-path: /boot-quick
spring:
  application:
    name: boot-quick
  jackson:
    time-zone: GMT+8
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:  # 不知道为啥只能查看一个数据源
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123456
        allow:
    dynamic:
      p6spy: false
      druid:
        initial-size: 5
        asyncInit: true
        max-active: 30
        min-idle: 10
        keep-alive: true
        max-wait: 60000
        use-unfair-lock: true
        # 回收连接相关
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 600000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: true
        test-on-return: false
        poolPreparedStatements: false
        max-open-prepared-statements: 20
        filters: stat,wall
        stat:
          slowSqlMillis: 3000   # 慢日志配置
          logSlowSql: true
          mergeSql: true
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
#          url: jdbc:p6spy:mysql://${mysql.master.host}:${mysql.master.port}/${mysql.master.db}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&tinyInt1isBit=false
          url: jdbc:mysql://${mysql.master.host}:${mysql.master.port}/${mysql.master.db}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&tinyInt1isBit=false
          username: ${mysql.master.username}
          password: ${mysql.master.password}
#          driver-class-name: com.p6spy.engine.spy.P6SpyDriver

        slave1:
#          url: jdbc:p6spy:mysql://${mysql.slave1.host}:${mysql.slave1.port}/${mysql.slave1.db}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&tinyInt1isBit=false
          url: jdbc:mysql://${mysql.slave1.host}:${mysql.slave1.port}/${mysql.slave1.db}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&tinyInt1isBit=false
          username: ${mysql.slave1.username}
          password: ${mysql.slave1.password}
#          driver-class-name: com.p6spy.engine.spy.P6SpyDriver  # 优化sql显示插件，对性能有一定影响
  # 国际化资源文件
  messages:
    basename: exception/exception
    use-code-as-default-message: false

#  redis:
#    cluster:
#      max-redirects: 3
#      nodes: localhost:6601,localhost:6602,localhost:6603
#    database: 0
#    jedis:
#      pool:
#        max-active: 100
#        max-idle: 10
#        min-idle: 0
#        max-wait: 800ms
#    timeout: 1000ms


  mail:
    username: 1041765757@qq.com                # 用来验证授权的邮件用户名
    password: gotartrfwuytbcji                # 根据QQ邮箱设置-账户里生成的第三方登陆授权码，可用来代替密码登陆
    host: smtp.qq.com                         # 邮件服务器类型
    properties.mail.smtp.ssl.enable: true # 用以支持授权码登陆

  rabbitmq:
    addresses: ${rabbit.address}
    username: ${rabbit.username}
    password: ${rabbit.password}
    virtualHost: /
    cache:
      channel:
        size: 100
        checkoutTimeout: 3000
      connection:
        mode: connection
        size:
    template:
      retry:
        enabled: true
        maxAttempts: 5
        initialInterval: 2000  # 第一次和第二次尝试传递消息之间的持续时间

#  rabbitmq:
#    addresses: localhost:5672
#    username: root
#    password: password
#    virtual-host: / # 创建的虚拟主机，可以简单理解为一个实例，所有队列交换器路由等都是在它的基础上，默认为/，最好自己新建一个
#    publisher-confirms: true # 消息被投递之后如何确保一定被正确投递或消费，开启conform模式
#    listener:
#      direct:
#        acknowledge-mode: manual  # 开启手动ack
#      simple:
#        acknowledge-mode: manual # 开启手动ack
#        retry:
#          enabled: false
#          max-attempts: 3
#          initial-interval: 3000 # 第一次和第二次尝试传递消息之间的持续时间
#        default-requeue-rejected: false


customs:  # 自定义的属性最好都写在custom前缀下，方便辨认
  global-properties:
    snowflakeWorkerId: 1      # worker Id can't be greater than 31 or less than 0
    snowflakeDataCenterId: 1  # dataCenterId Id can't be greater than 31 or less than 0
    ignoreErrorTraceProfile:  # 过滤将异常堆栈信息输出打前端接口返回值的环境
      - pre
      - prod
    exception200: true  # 异常模式， true标识使用异常时保证http状态码为200，使用返回数据标识具体异常
  message_secret: false # 是否加密传输websocket消息数据

  jwt:
    secret: WoshiyigefenshuajiangfenshuabenlingqiangwoyaobanaxinfangzishuadegengpiaoliangshualefangziyoushuangqiangaiyawodexiaobizibianyabianleYang
    expiredMinute: 1080  # jwt token过期时间，单位分钟
    refreshTokenMinute: 10  # 在jwt token有效时间剩余达到了这个时间（分钟），如果用户在线（即调用了任意接口）则服务端主动刷新用户token并返回，需要前端配合处理重新替换用户token
    ignores:  ## 接口用户认证请求拦截忽略路径
      - path: /quick-start/**
      - path: /authUser/**
      - path: /v2/*
      - path: /swagger-ui.html
      - path: /swagger-ui.html/*
      - path: /swagger-resources/**
      - path: /swagger/**
      - path: /webjars/**
      - path: /druid/**
      - path: /csrf
      - path: /app.js
      - path: /controller.html
      - path: /websocket.html
      - path: /js/*
      - path: /ws/*
      - path: /pay-ws/*
      - path: /heartCheck.txt
      - path: /authUser/registry
      - path: /authUser/loginByPassword
      - path: /index.html
      - path: /favicon.ico
  rsa:
    primaryKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIPT0VbUrdYMIX//tgHgaMh9PUtqG6R/lNOvIl9LR6Mbc5J03qjvLlu2IifHFbFonm6XguZG4LZ4H3hRkX9fC4qSaQR1vZBOvS1aNLRyvMZudISJygiag1qJOQMEwrb8JUZkP7NMpBNjYpmF344+25Il3axRnd1oVR4Hhp4tqEe1AgMBAAECgYBYv0i3BAbjitcirKuDJ+hi0K1rD8v8OkefGtAxByT7EYgEmNktMZgr9bmYvdZE0QGXwjhFfoHZVZUaEw+4h+vkJrXxv2FQHqTSL8fDeL4jggNO3YYpLFoq9bvwWeqDJ3vvVkJEbNycfoE6iXv91mUM3hb7ie1NlvWYOJtiAxf0AQJBAOzyLcea/8Au8nVnJrVstpVaItkib7pT/9w2BDAe821JTXsmUCGw47LpYHZos6G8pR9Hz8VRaj99z8Z5xa2fe2ECQQCObaUe0n67ddr3OExVF9LyFVEdGzvuOwJjQi6/URvhrQDV31kld2z9lqV6p2l6JpDpmQIwPsJTS7qbLLhjGqDVAkEAz+Gh3I/Wdiw6OFqpkV6xydLs5AfccmMkBXW2sulUtLstKTBx+T0SaHNsWDZ/8xRo4krEtN87Ej01P3KyxiM3wQJAaJirF5ycR40AtmeY3zD00KXJAOgcNhMN6NkUvZmSMUS9BVPWAwbWetEkS5QgiP1DlNmyWr3sNgG6U/UeoGFQ1QJAZief8zE0C5jCmWf7VwfAJCSd+r+BVcSCpUxskc3gnhfG6j+ImAirhXIY+ld8rArmGl4UPkQfapBphUJslWLpLg==
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCD09FW1K3WDCF//7YB4GjIfT1Lahukf5TTryJfS0ejG3OSdN6o7y5btiInxxWxaJ5ul4LmRuC2eB94UZF/XwuKkmkEdb2QTr0tWjS0crzGbnSEicoImoNaiTkDBMK2/CVGZD+zTKQTY2KZhd+OPtuSJd2sUZ3daFUeB4aeLahHtQIDAQAB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  ## mapper.xml文件所在路径
  mapper-locations: classpath:com/ddf/boot/quick/mapper/*.xml

leaf:
  name: com.sankuai.leaf.opensource.snowflake
  segment:
    enable: false
  snowflake:
    enable: true
    address: ${leaf.address}
    port: ${leaf.port}


logging:
  level:
    root: info
    com.ddf.boot.common.log.AccessLogAspect: debug
    com.ddf.boot.quick.mapper: debug
    com.ddf.boot.common.mq: debug

management:
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    jolokia:
      enabled: true