nacos:
  config:
    auto-refresh: true
    config-retry-time: 3000
    namespace: common
    group: DEFAULT_GROUP
    enable-remote-sync-config: false
    type: yaml
    data-ids: common-server,common-mybatis-plus,common-datasource,common-redis,common-mail,common-rabbitmq,common-rocketmq,common-mongo,common-es,common-elasticjob,common-xxl-job,common-jwt,common-global-properties,common-ext-oss,common-ext-sms,common-websocket,common-distributed-lock,common-ids
    ext-config:
      - namespace: spring-boot-quick
        dataId: property-source
        group: dev
        type: properties
        auto-refresh: true

      - dataId: config-properties
        type: properties
        auto-refresh: true

      - dataId: config-server
        type: yaml
        auto-refresh: true

customs: # 自定义的属性最好都写在custom前缀下，方便辨认
  zookeeper:
    monitor:
      connectAddress: ${zk_addr}

logging:
  level:
    root: info
    com.ddf.boot.common.log.AccessLogAspect: debug
    #    com.ddf.boot.quick.mapper: debug   因为用了sql插件，这里可以先注释掉
    com.ddf.boot.common.mq: debug
    com.ddf.boot.netty.broker: debug

