nacos:
  config:
    server-addr: ${nocos_server}
    username: ${nacos_username}
    password: ${nacos_password}
    auto-refresh: true
    config-retry-time: 3000
    namespace: dev
    enable-remote-sync-config: false
    type: properties
    data-id: property-source
    ext-config:
      - namespace: common
        dataId: common-server
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-mybatis-plus
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-datasource
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-redis
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-mail
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-rabbitmq
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-mongo
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-es
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-rocketmq
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-elasticjob
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-xxl-job
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-jwt
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-global-properties
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-ext-oss
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-ext-sms
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-websocket
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-distributed-lock
        type: yaml
        auto-refresh: true

      - namespace: common
        dataId: common-ids
        type: yaml
        auto-refresh: true

      - namespace: dev
        dataId: property-source
        type: properties
        auto-refresh: true

      - dataId: config-properties
        type: properties
        auto-refresh: true

      - dataId: config-server
        type: yaml
        auto-refresh: true

customs: # 自定义的属性最好都写在custom前缀下，方便辨认
  zookeeper:
    monitor:
      connectAddress: ${zk_addr}

logging:
  level:
    root: info
    com.ddf.boot.common.log.AccessLogAspect: debug
    #    com.ddf.boot.quick.mapper: debug   因为用了sql插件，这里可以先注释掉
    com.ddf.boot.common.mq: debug
    com.ddf.boot.netty.broker: debug

