# redis相关
redis_host: localhost
redis_port: 6379
redis_password: password

# redis集群
redis_node: localhost:6371,localhost:6372,localhost:6373,localhost:6374,localhost:6375,localhost:6376

# zookeeper地址,host:port, 多个用,隔开
zk_addr: localhost:2181,localhost:2182,localhost:2183

# mysql
mysql_host: localhost
mysql_port: 3306
mysql_db: boot-quick
mysql_username: username
mysql_password: password

# rabbitmq相关
rabbit_address: localhost:5672
rabbit_username: username
rabbit_password: password

# rocket name-server地址
rocketmq_name_server: localhost:9876

# mongo
mongodb_url: mongodb://develop:password@www.snowball.fans:27017/boot-quick?authSource=admin

# xxl-job
xxl_admin_addresses: http://localhost:8805
xxl_admin_access_token: token

## qq邮箱服务
mail_server_username: username
mail_server_password: password

## oss
oss_endpoint: wait_fill
oss_accessKeyId: wait_fill
oss_accessKeySecret: wait_fill
oss_secret: false
oss_stsEndpoint: wait_fill
oss_roleArn: wait_fill

# jwt
jwt_secret: wait_fill

# 动态RSA
rsa_primaryKey: wait_fill
rsa_publicKey: wait_fill

## druid
druid_stat_enable: false
druid_state_username: wait_fill
druid_state_password: wait_fill

## ES
es_hosts: host1:9200,host2:9200,host3:9200
es_username: username
es_password: password

## nacos
nocos_server: localhost:8848
nacos_username: nacos
nacos_password: nacos
# 在spring-boot应用中（注意不是spring-cloud），开启这个可以让spring-boot应用具备在启动前就将外部配置加载到spring环境中的能力， 即可通过外部配置各种数据源了
nacos:
  config:
    bootstrap:
      enable: true


server:
  port: 8080
  tomcat:
    threads:
      max: 400
      min-spare: 20
    max-connections: 10000
    processorCache: 400
    acceptCount: 200  # 最大等待队列长度
  servlet:
    context-path: /boot-quick
  shutdown: graceful # 配置web容器优雅关闭，https://docs.spring.io/spring-boot/docs/2.5.7/reference/htmlsingle/#features.graceful-shutdown
# 老版本
#    max-threads: 200
#    min-spare-threads: 20

spring:
  lifecycle:
    timeout-per-shutdown-phase: 60  # 优雅关闭等待时间，https://docs.spring.io/spring-boot/docs/2.5.7/reference/htmlsingle/#features.graceful-shutdown
  profiles:
    active: local
  application:
    name: boot-quick
  jackson:
    time-zone: GMT+8
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN

  # 国际化资源文件
  messages:
    basename: exception/exception
    use-code-as-default-message: false

customs: # 自定义的属性最好都写在custom前缀下，方便辨认
  global-properties:
    snowflakeWorkerId: 1      # worker Id can't be greater than 31 or less than 0
    snowflakeDataCenterId: 1  # dataCenterId Id can't be greater than 31 or less than 0
    ignoreErrorTraceProfile: # 过滤将异常堆栈信息输出打前端接口返回值的环境
      - pre
      - prod
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: null
      logic-delete-field: isDel
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    # https://mp.baomidou.com/config/#localcachescope
    localCacheScope: STATEMENT
  ## mapper.xml文件所在路径
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com.ddf.boot.common.log.AccessLogAspect: debug
    #    com.ddf.boot.quick.mapper: debug   因为用了sql插件，这里可以先注释掉
    com.ddf.boot.common.mq: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug

management:
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
    jolokia:
      enabled: true
