nacos:
  config:
    auto-refresh: true
    config-retry-time: 3000
    namespace: spring-boot-quick
    group: dev
    # 配置拉不下来的时候可以打开这个参数看下， 这个时候会有nacos的报错信息，虽然这个参数不是做这个作用的
    enable-remote-sync-config: true
    type: yaml
    data-id: config-server
    ext-config:
      - namespace: spring-boot-quick
        dataId: property-source
        group: dev
        type: properties
        auto-refresh: true
      - namespace: spring-boot-quick
        dataId: config-properties
        group: dev
        type: properties
        auto-refresh: true
      - namespace: spring-boot-quick
        dataId: config-server
        group: dev
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-server
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-mybatis-plus
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-datasource
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-redis
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-mail
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-rabbitmq
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-rocketmq
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-mongo
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-es
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-elasticjob
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-xxl-job
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-jwt
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-global-properties
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-ext-oss
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-ext-sms
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-websocket
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-distributed-lock
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true
      - namespace: common
        dataId: common-ids
        group: DEFAULT_GROUP
        type: yaml
        auto-refresh: true

customs: # 自定义的属性最好都写在custom前缀下，方便辨认
  zookeeper:
    monitor:
      connectAddress: ${zk_addr}

logging:
  level:
    root: info
    com.ddf.boot.common.log.AccessLogAspect: debug
    #    com.ddf.boot.quick.mapper: debug   因为用了sql插件，这里可以先注释掉
    com.ddf.boot.common.mq: debug
    com.ddf.boot.netty.broker: debug

