# mysql
mysql.host: localhost
mysql.port: 3306
mysql.db: boot-quick
mysql.username: root
mysql.password: 123456

server:
  port: 8080
  tomcat:
    max-connections: 20000
    max-threads: 400
    min-spare-threads: 20
  servlet:
    context-path: /boot-quick
spring:
  application:
    name: boot-quick
  jackson:
    time-zone: GMT+8
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
  main:
    allow-bean-definition-overriding: true

  # 经测试filter需要配置再datasource.druid下，而每个连接的信息还是得配置在sharding-sphere下的datasource每个自己的
  datasource:
    druid:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 3000
        wall:
          enabled: true # 开启WallFilter
          db-type: mysql
      ## 开启内置监控界面 访问路径: /context-path/druid/index.html
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123456

  shardingsphere:
    datasource:
      names: master,slave0,slave1
      # 配置数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.db}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&tinyInt1isBit=false
        username: ${mysql.username}
        password: ${mysql.password}
        initial-size: 5
        max-active: 20
        min-idle: 10
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        ## 回收连接相关
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        poolPreparedStatements: true
        max-open-prepared-statements: 20
        async-init: true
      # 配置数据源
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        slave0.driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/${mysql.db}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&tinyInt1isBit=false
        username: root
        password: 123456
        initial-size: 5
        max-active: 20
        min-idle: 10
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        ## 回收连接相关
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        poolPreparedStatements: true
        max-open-prepared-statements: 20
        async-init: true
      # 配置数据源
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        slave0.driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/${mysql.db}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&tinyInt1isBit=false
        username: root
        password: 123456
        initial-size: 5
        max-active: 20
        min-idle: 10
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        ## 回收连接相关
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        poolPreparedStatements: true
        max-open-prepared-statements: 20
        async-init: true

    # 配置主从规则
    masterslave:
      # 从库负载均衡算法
      load-balance-algorithm-type: round_robin
      # 读写分离数据源名称
      name: ms
      # 主库数据源名称， 从上面配置的数据源中选择
      master-data-source-name: master
      # 从库数据源名称列表， 从上面配置的数据源中选择
      slave-data-source-names: slave0,slave1

    props:
      #  显示sql具体信息
      sql.show: true

  # 国际化资源文件
  messages:
    basename: exception/exception
    use-code-as-default-message: false

  mail:
    username: 1041765757@qq.com                # 用来验证授权的邮件用户名
    password: gotartrfwuytbcji                # 根据QQ邮箱设置-账户里生成的第三方登陆授权码，可用来代替密码登陆
    host: smtp.qq.com                         # 邮件服务器类型
    properties.mail.smtp.ssl.enable: true # 用以支持授权码登陆

customs:  # 自定义的属性最好都写在custom前缀下，方便辨认
  global-properties:
    snowflakeWorkerId: 1      # worker Id can't be greater than 31 or less than 0
    snowflakeDataCenterId: 1  # dataCenterId Id can't be greater than 31 or less than 0
    ignoreErrorTraceProfile:  # 过滤将异常堆栈信息输出打前端接口返回值的环境
      - pre
      - prod
    exception200: true  # 异常模式， true标识使用异常时保证http状态码为200，使用返回数据标识具体异常

  jwt:
    secret: WoshiyigefenshuajiangfenshuabenlingqiangwoyaobanaxinfangzishuadegengpiaoliangshualefangziyoushuangqiangaiyawodexiaobizibianyabianleYang
    expiredMinute: 1080  # jwt token过期时间，单位分钟
    refreshTokenMinute: 10  # 在jwt token有效时间剩余达到了这个时间（分钟），如果用户在线（即调用了任意接口）则服务端主动刷新用户token并返回，需要前端配合处理重新替换用户token
    ignores:  ## 接口用户认证请求拦截忽略路径
      - path: /quick-start/**
      - path: /v2/*
      - path: /swagger-ui.html
      - path: /swagger-ui.html/*
      - path: /swagger-resources/**
      - path: /swagger/**
      - path: /webjars/**
      - path: /druid/**
      - path: /csrf
      - path: /app.js
      - path: /controller.html
      - path: /websocket.html
      - path: /js/*
      - path: /ws/*
      - path: /pay-ws/*
      - path: /heartCheck.txt
      - path: /authUser/registry
      - path: /authUser/loginByPassword
      - path: /index.html
      - path: /favicon.ico
  rsa:
    primaryKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIPT0VbUrdYMIX//tgHgaMh9PUtqG6R/lNOvIl9LR6Mbc5J03qjvLlu2IifHFbFonm6XguZG4LZ4H3hRkX9fC4qSaQR1vZBOvS1aNLRyvMZudISJygiag1qJOQMEwrb8JUZkP7NMpBNjYpmF344+25Il3axRnd1oVR4Hhp4tqEe1AgMBAAECgYBYv0i3BAbjitcirKuDJ+hi0K1rD8v8OkefGtAxByT7EYgEmNktMZgr9bmYvdZE0QGXwjhFfoHZVZUaEw+4h+vkJrXxv2FQHqTSL8fDeL4jggNO3YYpLFoq9bvwWeqDJ3vvVkJEbNycfoE6iXv91mUM3hb7ie1NlvWYOJtiAxf0AQJBAOzyLcea/8Au8nVnJrVstpVaItkib7pT/9w2BDAe821JTXsmUCGw47LpYHZos6G8pR9Hz8VRaj99z8Z5xa2fe2ECQQCObaUe0n67ddr3OExVF9LyFVEdGzvuOwJjQi6/URvhrQDV31kld2z9lqV6p2l6JpDpmQIwPsJTS7qbLLhjGqDVAkEAz+Gh3I/Wdiw6OFqpkV6xydLs5AfccmMkBXW2sulUtLstKTBx+T0SaHNsWDZ/8xRo4krEtN87Ej01P3KyxiM3wQJAaJirF5ycR40AtmeY3zD00KXJAOgcNhMN6NkUvZmSMUS9BVPWAwbWetEkS5QgiP1DlNmyWr3sNgG6U/UeoGFQ1QJAZief8zE0C5jCmWf7VwfAJCSd+r+BVcSCpUxskc3gnhfG6j+ImAirhXIY+ld8rArmGl4UPkQfapBphUJslWLpLg==
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCD09FW1K3WDCF//7YB4GjIfT1Lahukf5TTryJfS0ejG3OSdN6o7y5btiInxxWxaJ5ul4LmRuC2eB94UZF/XwuKkmkEdb2QTr0tWjS0crzGbnSEicoImoNaiTkDBMK2/CVGZD+zTKQTY2KZhd+OPtuSJd2sUZ3daFUeB4aeLahHtQIDAQAB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  ## mapper.xml文件所在路径
  mapper-locations: classpath:com/ddf/boot/quick/mapper/*.xml

logging:
  level:
    root: info
    com.ddf.boot.common.log.AccessLogAspect: debug
    com.ddf.boot.quick.mapper: debug
    com.ddf.boot.common.mq: debug

management:
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    jolokia:
      enabled: true