<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>spring-boot-quick</artifactId>
        <groupId>com.ddf.boot</groupId>
        <version>quickstart3.5-2025.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>quick-core</artifactId>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <ddf-common-core.version>boot3.5-2025.1-SNAPSHOT</ddf-common-core.version>
        <ddf-common-authentication.version>boot3.5-2025.1-SNAPSHOT</ddf-common-authentication.version>
        <ddf-common-mybatis-plus.version>boot3.5-2025.1-SNAPSHOT</ddf-common-mybatis-plus.version>
        <ddf-common-limit.version>boot3.5-2025.1-SNAPSHOT</ddf-common-limit.version>
        <ddf-common-redis.version>boot3.5-2025.1-SNAPSHOT</ddf-common-redis.version>
        <ddf-common-log4j.version>boot3.5-2025.1-SNAPSHOT</ddf-common-log4j.version>
        <ddf-common-mvc.version>boot3.5-2025.1-SNAPSHOT</ddf-common-mvc.version>
        <ddf-common-alarm.version>boot3.5-2025.1-SNAPSHOT</ddf-common-alarm.version>
        <ddf-common-captcha.version>boot3.5-2025.1-SNAPSHOT</ddf-common-captcha.version>
        <ddf-common-distributed-lock.version>boot3.5-2025.1-SNAPSHOT</ddf-common-distributed-lock.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ddf.boot</groupId>
            <artifactId>quick-api</artifactId>
            <version>quickstart3.5-2025.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-core</artifactId>
            <version>${ddf-common-core.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-alarm</artifactId>
            <version>${ddf-common-alarm.version}</version>
        </dependency>


        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-authentication</artifactId>
            <version>${ddf-common-authentication.version}</version>
        </dependency>

        <!-- 用于刷新配置 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-context</artifactId>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-limit</artifactId>
            <version>${ddf-common-limit.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-redis</artifactId>
            <version>${ddf-common-redis.version}</version>
        </dependency>


        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-captcha</artifactId>
            <version>${ddf-common-captcha.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-distributed-lock</artifactId>
            <version>${ddf-common-distributed-lock.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-log4j</artifactId>
            <version>${ddf-common-log4j.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-mvc</artifactId>
            <version>${ddf-common-mvc.version}</version>
            <!-- 排除默认日志依赖，如logback， 手动引入log4j依赖， 如果使用logback这里注释放开即可 -->
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter-logging</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <!-- 排除默认日志依赖，如logback， 手动引入log4j依赖， 如果使用logback这里注释放开即可 -->
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter-logging</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

    </dependencies>

    <build>
        <finalName>spring-boot-quick</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>com.ddf.boot.quickstart.core.Application</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
