<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>spring-boot-quick</artifactId>
        <groupId>com.ddf.spring-boot</groupId>
        <version>1.0.2-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>quick-core</artifactId>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <ddf-common-core.version>boot276-2025.2.0-SNAPSHOT</ddf-common-core.version>
        <ddf-common-authentication.version>boot276-2025.2.0-SNAPSHOT</ddf-common-authentication.version>
        <ddf-common-mybatis-plus.version>boot276-2025.2.0-SNAPSHOT</ddf-common-mybatis-plus.version>
        <ddf-common-limit.version>boot276-2025.2.0-SNAPSHOT</ddf-common-limit.version>
        <ddf-common-redis.version>boot276-2025.2.0-SNAPSHOT</ddf-common-redis.version>
        <ddf-common-captcha.version>boot276-2025.2.0-SNAPSHOT</ddf-common-captcha.version>
        <ddf-common-vps.version>boot276-2025.2.0-SNAPSHOT</ddf-common-vps.version>
        <ddf-common-third-party.version>boot276-2025.2.0-SNAPSHOT</ddf-common-third-party.version>
        <ddf-common-mongo.version>boot276-2025.2.0-SNAPSHOT</ddf-common-mongo.version>
        <ddf-common-sharding.version>boot276-2025.2.0-SNAPSHOT</ddf-common-sharding.version>
        <ddf-common-mq.version>boot276-2025.2.0-SNAPSHOT</ddf-common-mq.version>
        <ddf-common-netty-broker.version>boot276-2025.2.0-SNAPSHOT</ddf-common-netty-broker.version>
        <ddf-common-rocketmq.version>boot276-2025.2.0-SNAPSHOT</ddf-common-rocketmq.version>
        <ddf-common-websocket.version>boot276-2025.2.0-SNAPSHOT</ddf-common-websocket.version>
        <ddf-common-ids-service.version>boot276-2025.2.0-SNAPSHOT</ddf-common-ids-service.version>
        <ddf-common-es.version>boot276-2025.2.0-SNAPSHOT</ddf-common-es.version>
        <ddf-common-xxl-executor.version>boot276-2025.2.0-SNAPSHOT</ddf-common-xxl-executor.version>
        <ddf-common-log4j.version>boot276-2025.2.0-SNAPSHOT</ddf-common-log4j.version>
        <ddf-common-sentinel.version>boot276-2025.2.0-SNAPSHOT</ddf-common-sentinel.version>
        <ddf-common-mqtt.version>boot276-2025.2.0-SNAPSHOT</ddf-common-mqtt.version>
        <ddf-common-mvc.version>boot276-2025.2.0-SNAPSHOT</ddf-common-mvc.version>
        <ddf-common-alarm.version>boot276-2025.2.0-SNAPSHOT</ddf-common-alarm.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.ddf.spring-boot</groupId>
            <artifactId>quick-api</artifactId>
            <version>1.0.2-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-core</artifactId>
            <version>${ddf-common-core.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-alarm</artifactId>
            <version>${ddf-common-alarm.version}</version>
        </dependency>


        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-authentication</artifactId>
            <version>${ddf-common-authentication.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-third-party</artifactId>
            <version>${ddf-common-third-party.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-mqtt</artifactId>
            <version>${ddf-common-mqtt.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-sentinel</artifactId>
            <version>${ddf-common-sentinel.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-xxl-executor</artifactId>
            <version>${ddf-common-xxl-executor.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-es</artifactId>
            <version>${ddf-common-es.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>log4j-api</artifactId>
                    <groupId>org.apache.logging.log4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- 用于刷新配置 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-context</artifactId>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-sharding</artifactId>
            <version>${ddf-common-sharding.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-mongo</artifactId>
            <version>${ddf-common-mongo.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-rocketmq</artifactId>
            <version>${ddf-common-rocketmq.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-limit</artifactId>
            <version>${ddf-common-limit.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-ids-service</artifactId>
            <version>${ddf-common-ids-service.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-redis</artifactId>
            <version>${ddf-common-redis.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-netty-broker</artifactId>
            <version>${ddf-common-netty-broker.version}</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-captcha</artifactId>
            <version>${ddf-common-captcha.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-vps</artifactId>
            <version>${ddf-common-vps.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-websocket</artifactId>
            <version>${ddf-common-websocket.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-log4j</artifactId>
            <version>${ddf-common-log4j.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-mvc</artifactId>
            <version>${ddf-common-mvc.version}</version>
            <!-- 排除默认日志依赖，如logback， 手动引入log4j依赖， 如果使用logback这里注释放开即可 -->
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter-logging</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <!-- 排除默认日志依赖，如logback， 手动引入log4j依赖， 如果使用logback这里注释放开即可 -->
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter-logging</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

    </dependencies>

    <build>
        <finalName>spring-boot-quick</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
