<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>spring-boot-quick</artifactId>
        <groupId>com.ddf.spring-boot</groupId>
        <version>1.0.2-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>quick-core</artifactId>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <ddf-common-core.version>boot358-2025.12-SNAPSHOT</ddf-common-core.version>
        <ddf-common-authentication.version>boot358-2025.12-SNAPSHOT</ddf-common-authentication.version>
        <ddf-common-mybatis-plus.version>boot358-2025.12-SNAPSHOT</ddf-common-mybatis-plus.version>
        <ddf-common-limit.version>boot358-2025.12-SNAPSHOT</ddf-common-limit.version>
        <ddf-common-redis.version>boot358-2025.12-SNAPSHOT</ddf-common-redis.version>
        <ddf-common-captcha.version>boot358-2025.12-SNAPSHOT</ddf-common-captcha.version>
        <ddf-common-vps.version>boot358-2025.12-SNAPSHOT</ddf-common-vps.version>
        <ddf-common-third-party.version>boot358-2025.12-SNAPSHOT</ddf-common-third-party.version>
        <ddf-common-mongo.version>boot358-2025.12-SNAPSHOT</ddf-common-mongo.version>
        <ddf-common-sharding.version>boot358-2025.12-SNAPSHOT</ddf-common-sharding.version>
        <ddf-common-mq.version>boot358-2025.12-SNAPSHOT</ddf-common-mq.version>
        <ddf-common-netty-broker.version>boot358-2025.12-SNAPSHOT</ddf-common-netty-broker.version>
        <ddf-common-rocketmq.version>boot358-2025.12-SNAPSHOT</ddf-common-rocketmq.version>
        <ddf-common-websocket.version>boot358-2025.12-SNAPSHOT</ddf-common-websocket.version>
        <ddf-common-ids-service.version>boot358-2025.12-SNAPSHOT</ddf-common-ids-service.version>
        <ddf-common-es.version>boot358-2025.12-SNAPSHOT</ddf-common-es.version>
        <ddf-common-xxl-executor.version>boot358-2025.12-SNAPSHOT</ddf-common-xxl-executor.version>
        <ddf-common-log4j.version>boot358-2025.12-SNAPSHOT</ddf-common-log4j.version>
        <ddf-common-mqtt.version>boot358-2025.12-SNAPSHOT</ddf-common-mqtt.version>
        <ddf-common-mvc.version>boot358-2025.12-SNAPSHOT</ddf-common-mvc.version>
        <ddf-common-alarm.version>boot358-2025.12-SNAPSHOT</ddf-common-alarm.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-properties-migrator</artifactId>
            <version>3.5.8</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.ddf.spring-boot</groupId>
            <artifactId>quick-api</artifactId>
            <version>1.0.2-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-core</artifactId>
            <version>${ddf-common-core.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-redis</artifactId>
            <version>${ddf-common-redis.version}</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-log4j</artifactId>
            <version>${ddf-common-log4j.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-mvc</artifactId>
            <version>${ddf-common-mvc.version}</version>
            <!-- 排除默认日志依赖，如logback， 手动引入log4j依赖， 如果使用logback这里注释放开即可 -->
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter-logging</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <!-- 排除默认日志依赖，如logback， 手动引入log4j依赖， 如果使用logback这里注释放开即可 -->
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter-logging</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>


        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-sharding</artifactId>
            <version>${ddf-common-sharding.version}</version>
        </dependency>


    </dependencies>

    <build>
        <finalName>spring-boot-quick</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
