mysql_host: 192.168.10.6
spring:
  data:
    redis:
      host: 192.168.10.6
      port: 6379
      database: 1
      password: Aa&123456
customizer:
  infra:
    mqtt:
      connectionUrls:
        - protocol: mqtt_tcp
          url: tcp://192.168.10.11:21883
